### ISSUE TITLE
不匹配的测试用例

### ISSUE THREAD

**Issue by lynnux** [jcs-elpa/flx-rs#15]
```
(flx-rs-score "xxx/Ydsysctl/damsrv.cpp" "ydsvc cpp")
(flx-rs-score "xxx/Ydsysctl/damsrv.cpp" "ydsvc.cpp")
(flx-rs-score "xxx/ydsysctl/damsrv.cpp" "ydsvc cpp")
(flx-rs-score "xxx/ydsysctl/damsrv.cpp" "ydsvc.cpp")
```
目前测试了fussy列举的c后端和rust后端，就fzf-native表现最好，其它后端加油了！

**Comment by lynnux** [comment]
另外fzf-native支持分词反序，如
`(fussy-fzf-native-score "aaa/dlg_optimize.xml" "xml opt")`
而`(flx-rs-score "aaa/dlg_optimize.xml" "xml opt")`是不行的。注意这里有个空格是用来分词的，不加空格fzf-native就不支持了如`(flx-rs-score "aaa/dlg_optimize.xml" "xmlopt")`，不过对我来说这个可以接受，完全反序的话可能结果很多。

**Comment by jcs090218** [comment]
flx-rs 是基於 flx. 基本上就是照抄. 如果沒有意外的話，我想目前可能也不會去做改變。

**Comment by lynnux** [comment]
哦哦，我说结果跟flx差不多，原来如此啊。不过那边也是很久没更新了。。

**Comment by jcs090218** [comment]
有想法的話，可以分享看看～ 我自己本身是蠻愛用flx的，就是速度太慢，所以寫了flx-rs.

**Comment by lynnux** [comment]
样例有误：
(flx-rs-score "xxx/Ydsysctl/damsrv.cpp" "ydsvc cpp")   -> 一般flex都不支持空格分词，fzf-native是个例外。
(flx-rs-score "xxx/Ydsysctl/damsrv.cpp" "ydsvc.cpp")  -> 错误样例，fzf-native也不匹配
(flx-rs-score "xxx/ydsysctl/damsrv.cpp" "ydsvc cpp") -> 说明同上，只是这里小写而已
(flx-rs-score "xxx/ydsysctl/damsrv.cpp" "ydsvc.cpp") -> 说明同上，只是这里小写而已

(fussy-fzf-native-score "aaa/dlg_optimize.xml" "xml opt") -> 一般flex都不支持空格分词，fzf-native是个例外。

综上：flx没问题，本issue关闭
