### ISSUE TITLE
flx-rs.x86_64-unknown-linux-gnu.so caused block emacs start on AMD 7840HS （but, it work on intel CPU)

### ISSUE THREAD

**Issue by zw963** [jcs-elpa/flx-rs#18]
I install a new 7840HS laptop, this prebuild binary for linux not work on my machine.

I try compile myself use https://github.com/jcs090218/flx-rs use `cargo build --release`, it's seem like successful, but i can't find the `so` file get generated in release folder, only `libflx_rs.d` and `libflx_rs.rlib` got created on target/release, how to fix that?

Thanks.

**Comment by jcs090218** [comment]
I think it's because I've never built for linux ARM. It should be fixed in b3c1f57478f4f2870224263e479d5334c00d3651. Can you try upgrading to the latest?

**Comment by zw963** [comment]
> I think it's because I've never built for linux ARM.

Hi, maybe i misunderstood this, my processor is AMD 7840HS, it belongs to linux ARM?

> It should be fixed in [b3c1f57](https://github.com/jcs-elpa/flx-rs/commit/b3c1f57478f4f2870224263e479d5334c00d3651). Can you try upgrading to the latest?

Sorry for confusing, because test on my new installed laptop with fresh new Arch, several bianry is missing, my emacs daemon block by mu4e's binary `mu`, not flx-rs, in fact, the prebuilt binary work quite well for me. 

Thanks.
